server:
  port: 31008
  servlet:
    context-path: /project
spring:
  servlet:
    multipart:
      max-file-size: -1
  application:
    name: ig-project
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:31010/zb?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    maxActive: 20
    initialSize: 20
    maxWait: 2000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    username: root
    password: 123456
  redis:
    timeout: 6000ms
    password: Zdnsx@2017
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    port: 31011
eureka:
  instance:
    #hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123456@127.0.0.1:20001/eureka
      #defaultZone: http://admin:admin123456@29.23.3.44/eureka
mybatis:
  mapperLocations: classpath*:mapper/*.xml
logging:
  config: classpath:logback-spring.xml
# jasypt 密码加密配置
jasypt:
  encryptor:
    # 加密盐值
    password: zbjasypt
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    bean: customStringEncryptor
jwt:
  key: Cpic2020wzd


#feignClient配置
feign:
  httpclient:
    enabled: true
    connection-timeout: 50000
  hystrix:
    enabled: true #开启feign熔断
ribbon:
  ConnectTimeout: 50000 #请求连接的超时时间 默认的时间为 1 秒
  ReadTimeout: 50000  #请求处理的超时时间
  MaxAutoRetriesNextServer: 0 #不进行请求重发
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
#Feign
#feign.client.config.default.connectTimeout=10000
#feign.client.config.default.readTimeout=60000
  #Hystrix
  #hystrix.command.default.execution.timeout.enabled=true
  #hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=60000
  #Ribbon
  #ribbon.ConnectTimeout=10000
  #ribbon.ReadTimeout=60000

  #spring.servlet.multipart.enabled=true
  #spring.servlet.multipart.max-file-size=50MB
  #spring.servlet.multipart.max-request-size=50MB